Borgia_backend/Borgia/borgia/borgia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)

from django.contrib import admin
from django.urls import include, path

from borgia.views import ManagersWorkboard, MembersWorkboard, ModulesLoginView
from configurations.urls import configurations_patterns
from events.urls import events_patterns
from finances.urls import finances_patterns
from modules.urls import modules_patterns
from sales.urls import sales_patterns
from shops.urls import shops_patterns
from stocks.urls import stocks_patterns
from users.urls import users_patterns

urlpatterns = [
    path('api-auth/', include('rest_framework.urls',
                              namespace='rest_framework')),
    path('admin/', admin.site.urls),
    # AUTHENTIFICATIONS
    path('', ModulesLoginView.as_view(), name='url_login'),
    path(
        'auth/',
        include([
            path('login/', ModulesLoginView.as_view(), name='url_login'),
            path('logout/', LogoutView.as_view(), name='url_logout'),
            path('password_change/',
                 PasswordChangeView.as_view(),
                 name='password_change'),
            path('password_change/done/',
                 PasswordChangeDoneView.as_view(),
                 name='password_change_done'),
            path('password_reset/',
                 PasswordResetView.as_view(),
                 name='password_reset'),
            path('password_reset/done/',
                 PasswordResetDoneView.as_view(),
                 name='password_reset_done'),
            path('reset/<uidb64>/<token>/',
                 PasswordResetConfirmView.as_view(),
                 name='password_reset_confirm'),
            path('reset/done/',
                 PasswordResetCompleteView.as_view(),
                 name='password_reset_complete'),
        ])),
    # WORKBOARDS
    path('members/', MembersWorkboard.as_view(), name='url_members_workboard'),
    path('managers/',
         ManagersWorkboard.as_view(),
         name='url_managers_workboard'),

    ### APPS ###
    path('', include(configurations_patterns)),
    path('', include(events_patterns)),
    path('', include(finances_patterns)),
    path('', include(modules_patterns)),
    path('', include(sales_patterns)),
    path('', include(shops_patterns)),
    path('', include(stocks_patterns)),
    path('', include(users_patterns))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Cette ligne permet d'utiliser le dossier MEDIA en
# dev (en prod c'est automatique)

Borgia_backend/Borgia/borgia/sales/urls.py
from django.urls import include, path

from sales.views import SaleList, SaleRetrieve


sales_patterns = [

    path('shops/<int:shop_pk>/sales/', include([
        path('', SaleList.as_view(), name='url_sale_list'),
        path('<int:sale_pk>/', SaleRetrieve.as_view(),
        name='url_sale_retrieve')
    ]))
]

Borgia_backend/Borgia/borgia/users/urls.py
from . import views
from django.urls import include, path

from django.contrib import admin

from rest_framework import routers

from users.views import (GroupUpdateView, UserAddByListXlsxDownload,
                         UserCreateView, UserDeactivateView, UserListView,
                         UserRetrieveView, UserUpdateView,
                         UserUploadXlsxView, balance_from_username,
                         username_from_username_part)



# partie api
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)


#http://localhost:8000/api-links/users/users/?username=josue





users_patterns = [

    #API-AUTH

    path('api-links/profile/', views.ProfileView.as_view()),

    #path('api-links/admin/', admin.site.urls),
    path('api-links/login/', views.LoginView.as_view()),

    #API
    path('api-links/users/', include(router.urls)),

    #WEBSITE
    path('users/', include([
        path('', UserListView.as_view(), name='url_user_list'),
        path('create/', UserCreateView.as_view(), name='url_user_create'),
        path('<int:user_pk>/', include([
            path('', UserRetrieveView.as_view(), name='url_user_retrieve'),
            path('update/', UserUpdateView.as_view(), name='url_user_update'),
            path('deactivate/', UserDeactivateView.as_view(), name='url_user_deactivate')
        ])),

        path('add_by_list/xlsx/', UserUploadXlsxView.as_view(), name='url_add_by_list_xlsx'),
        path('add_by_list/xlsx/download/', UserAddByListXlsxDownload.as_view(), name='url_add_by_list_xlsx_download')
    ])),
    path('groups/<int:group_pk>/update/', GroupUpdateView.as_view(), name='url_group_update'),
    path('ajax/username_from_username_part/', username_from_username_part, name='url_ajax_username_from_username_part'),
    path('ajax/balance_from_username/', balance_from_username, name='url_balance_from_username')
]

Borgia_backend/Borgia/borgia/users/models.py
import datetime
import decimal
import itertools

from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone

from borgia.utils import (PRESIDENTS_GROUP_NAME, VICE_PRESIDENTS_GROUP_NAME, TREASURERS_GROUP_NAME,
                          INTERNALS_GROUP_NAME, EXTERNALS_GROUP_NAME)


class User(AbstractUser):
    """
    Extend the AbstractUser class from Django to define a common User class.

    note:: All attributes refer to the user state. For its group for instance
    (honnor member for example) please refer to the class Group (Django Auth
    app).

    Attributes:
    :param id: auto generated Django id for db, from AbstractUser, auto
    :param username: username of the user, from AbstractUser, mandatory
    :param last_name: last name of the user, from AbstractUser
    :param first_name: first name of the user, from AbstractUser
    :param password: hashed password of the user, from AbstractUser
    :param email: e-mail of the user, from AbstractUser
    :param surname: Gadz'Art surname of the user (ie. bucque)
    :param family: Gadz'Art family of the user (ie. fam'ss)
    :param balance: hard consolidated balance for the user account
    :param year: Gadz'Art promotion of the user (ie. prom'ss)
    :param campus: Gadz'Art centre of the user (ie. tabagn'ss)
    :param phone: phone number of the user (currently not used)
    :param avatar: image of the user
    :param theme: preference of css for the user
    :type id: integer superior to 0
    :type username: string only alpha numeric warning:: must be unique
    :type last_name: string
    :type first_name: string
    :type password: string note:: for more info about password management
    refer to Django doc _passwords:
    https://docs.djangoproject.com/en/1.10/topics/auth/passwords/
    :type email: string must match standard email regex
    :type surname: string
    :type family: string
    :type balance float
    :type year: string must be in YEAR_CHOICES
    :type campus: string must be in CAMPUS_CHOICES
    :type phone: string must match standard phone number in France ^0[0-9]{9}$
    :type avatar: string path of the image in statics
    :type theme: string must be in THEME_CHOICES

    """

    CAMPUS_CHOICES = (
        ('ME', 'Me'),
        ('AN', 'An'),
        ('CH', 'Ch'),
        ('BO', 'Bo'),
        ('LI', 'Li'),
        ('CL', 'Cl'),
        ('KA', 'Ka'),
        ('KIN', 'Kin')
    )
    YEAR_CHOICES = []
    for i in range(1953, datetime.datetime.now().year + 1):
        YEAR_CHOICES.append((i, i))

    THEME_CHOICES = (
        ('light', 'Light'),
        ('dark', 'Dark'),
        ('birse', 'Birse')
    )

    surname = models.CharField('Bucque', max_length=255, blank=True, null=True)
    family = models.CharField('Fam\'ss', max_length=255, blank=True, null=True)
    balance = models.DecimalField('Solde', default=0, max_digits=9,
                                  decimal_places=2)
    virtual_balance = models.DecimalField('Solde prévisionnel', default=0, max_digits=9,
                                          decimal_places=2)
    year = models.IntegerField('Prom\'ss', choices=YEAR_CHOICES, blank=True,
                               null=True)
    campus = models.CharField('Tabagn\'ss', choices=CAMPUS_CHOICES,
                              max_length=3, blank=True, null=True)
    phone = models.CharField('Numéro de téléphone', max_length=255,
                             blank=True, null=True,
                             validators=[RegexValidator('^0[0-9]{9}$',
                                                        """Le numéro doit être
                                                        du type
                                                        0123456789""")])
    avatar = models.ImageField('Avatar', upload_to='img/avatars/',
                               default=None, blank=True, null=True)
    theme = models.CharField('Préférence de theme graphique', choices=THEME_CHOICES,
                             max_length=15, blank=True, null=True)

    jwt_iat = models.DateTimeField('Jwt iat', default=timezone.now)

    class Meta:
        """
        Define Permissions for User.

        :note:: Initial Django Permission (add, change, delete, view) are added.
        """
        permissions = (
            # Group management
            ("manage_" + PRESIDENTS_GROUP_NAME + \
             "_group", 'Can manage presidents group'),
            ("manage_" + VICE_PRESIDENTS_GROUP_NAME + \
             "_group", 'Can manage vice presidents group'),
            ("manage_" + TREASURERS_GROUP_NAME + \
             "_group", 'Can manage treasurers group'),
            ("manage_" + INTERNALS_GROUP_NAME + "_group", 'Can manage members group'),
            ("manage_" + EXTERNALS_GROUP_NAME + \
             "_group", 'Can manage externals group'),

            # User management
            # add_user
            # change_user
            # delete_user
            # view_user
            ('advanced_view_user', "Can view advanced data on user"),
        )

    def __str__(self):
        """
        Return the common string representing an instance of the class User.

        Returns the first name followed by the last name of the user.
        example:: Alexandre Palo
        If the first name or the last name is missing, return the username.

        :returns: string, undefined if no last or first name (not mandatory)
        """

        if not self.first_name or not self.last_name:
            return self.username
        else:
            return self.first_name + ' ' + self.last_name

    def get_full_name(self):
        """
        Return the name displayed in the navbar

        """
        if not self.first_name or not self.last_name:
            return self.username
        try:
            if not self.surname or not self.family:
                return self.first_name + ' ' + self.last_name
            else:
                return self.surname + ' ' + self.family + self.campus + self.year_pg()
        except AttributeError:
            return self.username

    def year_pg(self):
        """
        Return the promotion's year of the user, under the Gadz'Art standard.

        For ABCD year, this function returns ACD. The attribute year is not
        mandatory, the function will raise an error if there is no year.
        example:: 2014 -> 214

        :returns:  string
        :raises: AttributeError when no year

        """
        if self.year is not None:
            year = str(self.year)
            return year[:1] + year[-2:]
        else:
            return ""

    def forecast_balance(self):
        """
        Get all undone shared events where user is involved as participant

        TODO : Strongly dependent of events, should be moved there.
        """
        events = self.event_set.filter(done=False)
        solde_prev = 0
        for se in events:
            solde_prev += se.get_price_of_user(self)
        self.virtual_balance = self.balance - solde_prev
        self.save()

    def credit(self, amount):
        """
        Credit the user of a certain amount of money.

        note:: In both credit and debit cases, the amount must be positiv.
        There is no function allowed to credit or debit a negativ amount.

        :param amount: float or integer amount of money in euro, max 2 decimal
        places, must be superior to 0
        :returns: nothing
        :raise: ValueError if the amount is negative or null or if not a float
        or int
        """
        if (not isinstance(amount, int)) and (not isinstance(amount, float)) and (not isinstance(amount, decimal.Decimal)):
            raise ValueError('The amount is not a number')
        if amount <= 0:
            raise ValueError('The amount must be positive')

        self.balance += amount
        self.save()

    def debit(self, amount):
        """
        Debit the user of a certain amount of money.

        note:: In both credit and debit cases, the amount must be positive.
        There is no function allowed to credit or debit a negative amount.

        :param amount: float or integer amount of money in euro, max 2 decimal
        places, must be superior to 0
        :returns: nothing
        :raise: ValueError if the amount is negative or null or if not a float
        or int
        """
        if (not isinstance(amount, int)) and (not isinstance(amount, float)) and (not isinstance(amount, decimal.Decimal)):
            raise ValueError('The amount is not a number')
        if amount <= 0:
            raise ValueError('The amount must be strictly positive')

        self.balance -= amount
        self.save()

    def list_transaction(self):
        """
        Return the list of sales concerning the user.

        :returns: list of objects
        """

        sales = self.sender_sale.all()
        transferts = self.recipient_transfert.union(
            self.sender_transfert.all())
        rechargings = self.sender_recharging.all()
        exceptionnal_movements = self.recipient_exceptionnal_movement.all()
        events = self.event_set.filter(done=True)
        for event in events:
            event.amount = event.get_price_of_user(self)

        list_transaction = sorted(
            list(itertools.chain(sales, transferts, rechargings,
                                 exceptionnal_movements, events)),
            key=lambda instance: instance.datetime, reverse=True
        )

        return list_transaction


def get_list_year():
    """
    Return the list of current used years in all the users.

    :returns: list of integer years used by users, by decreasing dates.
    """
    list_year = []
    # For each user except admin
    for user in User.objects.filter(is_active=True).exclude(pk=1):
        if user.year not in list_year:
            if user.year is not None:  # year is not mandatory

Borgia_backend/Borgia/borgia/users/templates/users/bulk_edit.html
{% extends 'base_sober.html' %}
{% load bootstrap %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-fr_FR.min.js"></script>

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Upload d'utilisateurs via un fichier Excel
            </div>
            <div class="panel-body">
                <form enctype="multipart/form-data"
                      action="{% url 'url_add_by_list_xlsx' %}"
                      method='post'
                      class="form-horizontal">
                    {% csrf_token %} {{ upload_form|bootstrap_horizontal }}
                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-2">
                            <button type="submit"
                                    class="btn btn-success">Upload</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Téléchargement de fichiers Excels
            </div>
            <div class="panel-body">
                <form action="{% url 'url_add_by_list_xlsx_download' %}"
                      method="get"
                      class="form-horizontal">
                    {{ download_form|bootstrap_horizontal }}
                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-2">
                            <button type="submit"
                                    class="btn btn-primary">Télécharger l'Excel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <i class="fa fa-info-circle"
           aria-hidden="true"></i> Informations
    </div>
    <div class="panel-body">
        <p>Cette page permet d'ajouter ou de mettre à jour les données des utilisateurs depuis un fichier Excel.</p>
        <p><strong>Merci de bien vérifier l'email</strong> ! En effet, le mot de passe est généré aléatoirement, et chaque utilisateur devra faire une demande de réinitialisation par email. Autrement dit, s'il est faux, le compte ne sera pas accessible
            de leur part.
        </p>
        <br />
        <p>Le fichier Excel doit contenir les colonnes ci-dessous, seul le username est requis. L'ordre des colonnes n'est pas important.</p>

        <table class="table">
            <thead>
                <tr>
                   <th>username</th>
                   <th>first_name</th>
                   <th>last_name</th>
                   <th>campus</th>
                   <th>year</th>
                   <th>surname</th>
                   <th>family</th>
                   <th>phone</th>
                   <th>email</th>				   
                </tr>
            </thead>
        </table>		
    </div>
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/users/templates/users/group_update.html
{% extends 'base_sober.html' %}
{% load bootstrap %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-fr_FR.min.js"></script>

<div class="panel panel-primary">
  <div class="panel-heading">
    Gestion du groupe {{ group.name }}
  </div>
  <div class="panel-body">
    <form action= "" method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button class="btn btn-success" type="submit">Valider</button>
    </form>
  </div>
</div>

{% endblock %}

Borgia_backend/Borgia/borgia/users/templates/users/user_create.html
{% extends 'base_sober.html' %}
{% load bootstrap %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        Ajout d'un utilisateur
    </div>
    <div class="panel-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|bootstrap }}
            <button class="btn btn-success" type="submit">Ajouter</button>
        </form>
    </div>
</div>
<script>
  $("#id_family").change(function() {
    update_username()
  })
  $("#id_campus").change(function() {
    update_username()
  })
  $("#id_year").change(function() {
    update_username()
  })
  String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  }
  function update_username() {
    var username = ""
    username = (
      $("#id_family").val()
      + $("#id_campus").val().toLowerCase().capitalize()
      + $("#id_year").val().slice(0, 1) + $("#id_year").val().slice(2, 4))
    $("#id_username").val(username)
  }
</script>
{% endblock %}

Borgia_backend/Borgia/borgia/users/templates/users/user_deactivate.html
{% extends 'base_sober.html' %}

{% block content %}
<div class="panel panel-danger">
  <div class="panel-heading">
    {% if user.is_active == True %}
        Désactivation
    {% else %}
        Réactivation
    {% endif %}
    {% if user.pk == request.user.pk %}
        de mon compte
    {% else %}
        d'un compte utilisateur
    {% endif %}
  </div>
  <div class="panel-body">
    <form action="" method="post">
      {% csrf_token %}
      <label>
        {% if user.is_active == True %}
            Désactiver
        {% else %}
            Activer
        {% endif %}
            {% if user.pk == request.user.pk %}
                mon compte ?
            {% else %}
                l'utilisateur {{ user.username }} ({{ user.first_name }} {{ user.last_name }}) ?
            {% endif %}
	  </label>

        <input type=hidden name="is_active" value="{{ user.is_active }}" />
        <button class="btn btn-danger" type="submit">Valider</button>
    </form>
    {% if user.pk == request.user.pk %}
        <ul>
          <li>Attention! Une fois le compte désactivé, vous ne pouvez pas le réactiver vous-même.</li>
          <li>Vous ne pouvez pas désactiver votre compte tant que vous gérez des évènements en cours.
		      Depuis la page de gestion de l'évènement, il est possible d'assigner un autre gestionnaire.</li>
        </ul>
    {% endif %}
  </div>
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/users/templates/users/user_list.html
{% extends 'base_sober.html' %}
{% load users_extra %}
{% load bootstrap %}

{% block content %}
<div class="panel panel-primary">
  <div class="panel-heading">
    Utilisateurs

    {% if request.user|has_perm:"users.add_user" %}
        <div class="btn-group pull-right" role="group" aria-label="change user">
          <a class="btn btn-xs btn-warning" href="{% url 'url_add_by_list_xlsx' %}">Upload et téléchargement</a>
          <a class="btn btn-xs btn-success" href="{% url 'url_user_create' %}">Nouveau</a>
        </div>
    {% endif %}
  </div>
  <div class="panel-body">
    <form action="{% url 'url_user_list' %}" method="post" class="form-horizontal">
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
          <button type="submit" class="btn btn-primary">Recherche</button>
          <a class="btn btn-warning" href="{% url 'url_user_list' %}">Remise à zéro</a>
        </div>
      </div>
    </form>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    Résultats
  </div>
    {% if user_list %}
    <table class="table table-hover table-striped">
    <thead>


      <tr>
        {% for name, description in list_header %}
          <th><a href="?sort={{ name }}">{{ description }}
            {% if sort and sort == name %}
              {% if reverse %}
                <i class="fa fa-sort-desc" aria-hidden="true"></i>
              {% else %}
                <i class="fa fa-sort-asc" aria-hidden="true"></i>
              {% endif %}
            {% else %}
              <i class="fa fa-sort" aria-hidden="true"></i>
            {% endif %}
          </a></th>
        {% endfor %}
            <th>Détail</th>
      </tr>
    </thead>
    <tbody>
      {% for user in user_list %}
      <tr class="{% if user.balance >= 0 %}success{% else %}danger{% endif %}">
        <td>{{ user.username }}</td>
        <td>{{ user.last_name }} {{ user.first_name }}</td>
        <td>{{ user.surname }}</td>
        <td>{{ user.family }}</td>
        <td>{{ user.campus }}</td>
        <td>{{ user.year }}</td>
        <td>{{ user.balance }}€</td>
          <td>
            <a href="{% url 'url_user_retrieve' user_pk=user.pk %}">Détail</a>
          </td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
    {% else %}
        <div class="panel-body">
            Aucun utilisateur ne correspond à cette recherche.
        </div>
    {% endif %}
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/users/templates/users/user_quick_search.html
{% load bootstrap %}

<div class="panel panel-default">
    <div class="panel-heading">
        Recherche rapide d'un utilisateur
    </div>
    <div class="panel-body">
      <form action="{% url 'url_user_list' %}" method="post" class="form-horizontal" role="search_user">
        {% csrf_token %}
        <div class="form-group col-md-9">
          {{ quick_user_search_form.search  }}
          <span class="glyphicon glyphicon-user"></span>
        </div>

        <div class="form-group">
          <div class="col-md-3">
            <button type="submit" class="btn btn-primary">Recherche</button>
          </div>
        </div>
      </form>
      <a class="btn btn-info btn-xs pull-right" href="{% url 'url_user_list' %}">
          Accéder à la liste des utilisateurs
      </a>
    </div>
</div>

Borgia_backend/Borgia/borgia/users/templates/users/user_retrieve.html
{% extends 'base_sober.html' %}
{% load finances_extra %}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    Détails de l'utilisateur
      <div class="btn-group" role="group" aria-label="change user">
        {% if request.user|has_perm:"users.change_user" %}
          <a class="btn btn-primary" href="{% url 'url_user_update' user_pk=user.pk %}">Modifier les informations</a>
        {% endif %}
        {% if request.user|has_perm:"users.delete_user" or user.pk == request.user.pk %}
          <a class="btn btn-primary" href="{% url 'url_user_deactivate' user_pk=user.pk %}">
            {% if user.is_active == True %}
              Désactiver le compte
            {% else %}
              Activer le compte
            {% endif %}
          </a>
        {% endif %}
        {% if request.user|has_perm:"finances.add_exceptionnalmovement" %}
          <a class="btn btn-primary" href="{% url 'url_user_exceptionnalmovement_create' user_pk=user.pk %}">Mouvement exceptionnel</a>
        {% endif %}
        {% if request.user|has_perm:"finances.add_recharging" %}
          <a class="btn btn-primary" href="{% url 'url_recharging_create' user_pk=user.pk %}">Ajout d'argent</a>
        {% endif %}
      </div>
  </div>
  <div class="panel-body">
    <div class="row">
        {% include "users/partials/display_user_data.html" %}
    </div>
  </div>
</div>
{% if request.user|has_perm:"users.advanced_view_user" %}
<div class="panel panel-default">
  <div class="panel-heading">
    Dernières transactions
  </div>
  <table class="table table-default table-striped table-hover">
    <thead>
      <tr>
        <th>Date</th>
        <th>Libellé</th>
        <th>Montant</th>
        {% if request.user|has_perm:"finances.view_sale" %}
          <th>Détail</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for transaction in user.list_transaction|slice:":25" %}
      {% price_for sale=transaction user=user as price_for %}
      <tr class="
      {% if transaction|get_transaction_model == 'Sale' %}
        danger
      {% elif transaction|get_transaction_model == 'ExceptionnalMovement' %}
        {% if transaction.is_credit %}
          success
        {% else %}
          danger
        {% endif %}
      {% elif transaction|get_transaction_model == 'Transfert' %}
        {% if transaction.recipient == user %}
          success
        {% else %}
          danger
        {% endif %}
      {% elif transaction|get_transaction_model == 'Events' %}
        danger
      {% else %}
        success
      {% endif %}
      ">
        <td>{{ transaction.datetime }}</td>
        <td>
          {{ transaction }}
        </td>
        <td>
          {% if transaction|get_transaction_model == 'Sale' %}
            -{{ transaction.amount }}€
          {% elif transaction|get_transaction_model == 'ExceptionnalMovement' %}
            {% if transaction.is_credit %}
              {{ transaction.amount }}€
            {% else %}
              -{{ transaction.amount }}€
            {% endif %}
          {% elif transaction|get_transaction_model == 'Transfert' %}
            {% if transaction.recipient == user %}
              {{ transaction.amount }}€
            {% else %}
              -{{ transaction.amount }}€
            {% endif %}
          {% elif transaction|get_transaction_model == 'Event' %}
              -{{ transaction.amount }}€
          {% else %}
            {{ transaction.amount }}€
          {% endif %}
        </td>
        {% if request.user|has_perm:"finances.view_sale" %}
          <td><a href="
            {% if transaction|get_transaction_model == 'Recharging' %}
              {% url 'url_recharging_retrieve' recharging_pk=transaction.pk %}
            {% elif transaction|get_transaction_model == 'Transfert' %}
              {% url 'url_transfert_retrieve' transfert_pk=transaction.pk %}
            {% elif transaction|get_transaction_model == 'ExceptionnalMovement' %}
              {% url 'url_exceptionnalmovement_retrieve' exceptionnalmovement_pk=transaction.pk %}
            {% endif %}
            ">Détail</a></td>
          {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}
{% endblock %}

Borgia_backend/Borgia/borgia/users/templates/users/user_self_update.html
{% extends 'base_sober.html' %}
{% load bootstrap %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        Modifier ses informations
    </div>
    <div class="panel-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|bootstrap }}
            <a class="btn btn-warning" href="{% url 'password_change' %}">Modifier son mot de passe</a>
            <button class="btn btn-success" type="submit">Valider</button>
        </form>
    </div>
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/users/templates/users/user_update.html
{% extends 'base_sober.html' %}
{% load bootstrap %}

{% block content %}
<div class="panel panel-warning">
  <div class="panel-heading">
    Modification des informations de {{ user }}
  </div>
  <div class="panel-body">
    <form enctype="multipart/form-data" action="" method="post">
      {% csrf_token %}
      <span id="form">
      {{ form|bootstrap }}
      </span>
      <button class="btn btn-warning" type="submit">Modifier</button>
    </form>
  </div>
</div>
{% endblock %}