Borgia_backend/Borgia/borgia/borgia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)

from django.contrib import admin
from django.urls import include, path

from borgia.views import ManagersWorkboard, MembersWorkboard, ModulesLoginView
from configurations.urls import configurations_patterns
from events.urls import events_patterns
from finances.urls import finances_patterns
from modules.urls import modules_patterns
from sales.urls import sales_patterns
from shops.urls import shops_patterns
from stocks.urls import stocks_patterns
from users.urls import users_patterns

urlpatterns = [
    path('api-auth/', include('rest_framework.urls',
                              namespace='rest_framework')),
    path('admin/', admin.site.urls),
    # AUTHENTIFICATIONS
    path('', ModulesLoginView.as_view(), name='url_login'),
    path(
        'auth/',
        include([
            path('login/', ModulesLoginView.as_view(), name='url_login'),
            path('logout/', LogoutView.as_view(), name='url_logout'),
            path('password_change/',
                 PasswordChangeView.as_view(),
                 name='password_change'),
            path('password_change/done/',
                 PasswordChangeDoneView.as_view(),
                 name='password_change_done'),
            path('password_reset/',
                 PasswordResetView.as_view(),
                 name='password_reset'),
            path('password_reset/done/',
                 PasswordResetDoneView.as_view(),
                 name='password_reset_done'),
            path('reset/<uidb64>/<token>/',
                 PasswordResetConfirmView.as_view(),
                 name='password_reset_confirm'),
            path('reset/done/',
                 PasswordResetCompleteView.as_view(),
                 name='password_reset_complete'),
        ])),
    # WORKBOARDS
    path('members/', MembersWorkboard.as_view(), name='url_members_workboard'),
    path('managers/',
         ManagersWorkboard.as_view(),
         name='url_managers_workboard'),

    ### APPS ###
    path('', include(configurations_patterns)),
    path('', include(events_patterns)),
    path('', include(finances_patterns)),
    path('', include(modules_patterns)),
    path('', include(sales_patterns)),
    path('', include(shops_patterns)),
    path('', include(stocks_patterns)),
    path('', include(users_patterns))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Cette ligne permet d'utiliser le dossier MEDIA en
# dev (en prod c'est automatique)

Borgia_backend/Borgia/borgia/sales/urls.py
from django.urls import include, path

from sales.views import SaleList, SaleRetrieve


sales_patterns = [

    path('shops/<int:shop_pk>/sales/', include([
        path('', SaleList.as_view(), name='url_sale_list'),
        path('<int:sale_pk>/', SaleRetrieve.as_view(),
        name='url_sale_retrieve')
    ]))
]

Borgia_backend/Borgia/borgia/stocks/urls.py
from django.urls import include, path

from stocks.views import (InventoryListView, InventoryRetrieveView,
                          InventoryCreateView, StockEntryCreateView,
                          StockEntryListView, StockEntryRetrieveView)


stocks_patterns = [
    path('shops/<int:shop_pk>/stocks/', include([
        path('entries/', include([
            path('', StockEntryListView.as_view(), name='url_stockentry_list'),
            path('create/', StockEntryCreateView.as_view(), name='url_stockentry_create'),
            path('<int:stockentry_pk>/', StockEntryRetrieveView.as_view(), name='url_stockentry_retrieve'),
        ])),
        path('inventories/', include([
            path('', InventoryListView.as_view(), name='url_inventory_list'),
            path('create/', InventoryCreateView.as_view(), name='url_inventory_create'),
            path('<int:inventory_pk>/', InventoryRetrieveView.as_view(), name='url_inventory_retrieve'),
        ]))
    ]))
]

Borgia_backend/Borgia/borgia/sales/models.py
import decimal

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.timezone import now

from shops.models import Product, Shop
from users.models import User


class Sale(models.Model):
    """
    Define a Sale between two users.

    The transaction is managed by an operator (which can the the sender
    directly if the sell is direct). Most of sale are between an User and the
    association (represented by the special User with username 'AE ENSAM').

    :param datetime: date of sell, mandatory.
    :param sender: sender of the sale, mandatory.
    :param recipient: recipient of the sale, mandatory.
    :param operator: operator of the sale, mandatory.

    NEW IMPLMENTATION
    :param content_type:
    :param module_id:
    :param module:
    :param shop:
    :param products:


    :type datetime: date string, default now
    :type sender: User object
    :type recipient: User object
    :type operator: User object

    NEW IMPLMENTATION
    :type content_type:
    :type module_id:
    :type module:
    :type shop: Shop object
    :type products: Product object

    :note:: Initial Django Permission (add, change, delete, view) are added.
    """
    datetime = models.DateTimeField('Date', default=now)
    sender = models.ForeignKey(User, related_name='sender_sale',
                               on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='recipient_sale',
                                  on_delete=models.CASCADE)
    operator = models.ForeignKey(User, related_name='operator_sale',
                                 on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    module_id = models.PositiveIntegerField()
    module = GenericForeignKey('content_type', 'module_id')
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='SaleProduct')

    def __str__(self):
        """
        Return the display name of the Sale.

        :returns: pk of sale
        :rtype: string
        """
        return 'Achat ' + self.shop.__str__() + ', ' + self.string_products()

    def pay(self):
        self.sender.debit(self.amount())

    def string_products(self):
        """
        Return a formated string concerning all products in this Sale.

        :returns: each __str__ of products, separated by a comma.
        :rtype: string

        :note:: Why do Events are excluded ?
        """
        string = ''
        for sp in self.saleproduct_set.all():
            string += sp.__str__() + ', '
        string = string[0: len(string)-2]
        return string

    def from_shop(self):
        try:
            return self.module.shop
        except ObjectDoesNotExist:
            return None
        except IndexError:
            return None

    def amount(self):
        amount = 0
        for sale_product in self.saleproduct_set.all():
            amount += sale_product.price
        return amount


class SaleProduct(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField('Prix', default=0, decimal_places=2,
                                max_digits=9,
                                validators=[MinValueValidator(decimal.Decimal(0))])

    class Meta:
        """
        Remove default permissions for StockEntryProduct
        """
        default_permissions = ()

    def __str__(self):
        if self.product.unit:
            return self.product.__str__() + ' x ' + str(self.quantity) + self.product.get_unit_display()
        else:
            if self.quantity > 1:
                return self.product.__str__() + ' x ' + str(self.quantity)
            else:
                return self.product.__str__()

Borgia_backend/Borgia/borgia/stocks/forms.py
from django import forms
from django.forms.formsets import BaseFormSet

from shops.models import Product, Shop


class StockEntryProductForm(forms.Form):
    def __init__(self, *args, **kwargs):
        shop = kwargs.pop('shop')
        super().__init__(*args, **kwargs)
        product_choice = ([(None, 'Sélectionner un produit')] +
                          [(str(product.pk)+'/'+str(product.get_unit_display()), product.__str__())
                           for product in Product.objects.filter(shop=shop, is_removed=False)]
                          )
        self.fields['product'].choices = product_choice

    product = forms.ChoiceField(label='Produit', widget=forms.Select(
        attrs={'class': 'form-control selectpicker',
               'data-live-search': 'True', 'required': 'required'}))

    quantity = forms.IntegerField(
        label='En vente',
        widget=forms.NumberInput(
            attrs={'class': 'form-control centered_input quantity',
                   'placeholder': 'Quantité',
                   'min': 1, 'required': 'required'}),
        required=False
    )
    unit_quantity = forms.ChoiceField(
        label='Unité quantité',
        choices=([('UNIT', 'produits'), ('CL', 'cl'),
                  ('L', 'L'), ('G', 'g'), ('KG', 'kg')]),
        widget=forms.Select(
            attrs={'class': 'form-control selectpicker unit_quantity', 'required': 'required'}),
        required=False
    )
    amount = forms.DecimalField(
        label='Prix (€)',
        decimal_places=2,
        max_digits=9,
        widget=forms.NumberInput(
            attrs={'class': 'form-control centered_input amount',
                   'placeholder': 'Montant',
                   'min': 0, 'required': 'required'})
    )
    unit_amount = forms.ChoiceField(
        label='Unité montant',
        choices=([('UNIT', '€ / unité'), ('PACKAGE', '€ / lot'),
                  ('L', '€ / L'), ('KG', '€ / kg')]),
        widget=forms.Select(
            attrs={'class': 'form-control selectpicker unit_amount', 'required': 'required'}),
        required=False
    )
    inventory_quantity = forms.IntegerField(
        label='Stocks restant',
        widget=forms.NumberInput(
            attrs={'class': 'form-control centered_input quantity',
                   'placeholder': 'Stocks rest.',
                   'min': 0}),
        required=False
    )
    unit_inventory = forms.ChoiceField(
        label='Unité quantité',
        choices=([('UNIT', 'produits'), ('CL', 'cl'),
                  ('L', 'L'), ('G', 'g'), ('KG', 'kg')]),
        widget=forms.Select(
            attrs={'class': 'form-control selectpicker unit_quantity'}),
        required=False
    )

    # TODO : Validation


class BaseInventoryProductFormSet(BaseFormSet):
    def clean(self):
        """
        Check that there is max one inventory for each product
        """
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return

        products = []
        for form in self.forms:
            product = form.cleaned_data['product'].split('/')[0]

            if product in products:
                raise forms.ValidationError(
                    "Impossible de définir deux produits identiques dans le même inventaire")
            products.append(product)


class AdditionnalDataStockEntryForm(forms.Form):
    isAddingInventory = forms.ChoiceField(label='Faire également un inventaire des stocks',
                                          choices=([('with', 'Avec'), ('without', 'Sans')]))


class StockEntryListDateForm(forms.Form):
    def __init__(self, **kwargs):
        shop = kwargs.pop('shop')
        super().__init__(**kwargs)
        if shop is None:
            self.fields['shop'] = forms.ModelChoiceField(
                label='Magasin',
                queryset=Shop.objects.all(),
                empty_label='Tous',
                required=False
            )
    date_begin = forms.DateField(
        label='Date de début',
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(attrs={'class': 'datepicker'}),
        required=False
    )
    date_end = forms.DateField(
        label='Date de fin',
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(attrs={'class': 'datepicker'}),
        required=False
    )


class AdditionnalDataInventoryForm(forms.Form):
    type = forms.ChoiceField(label='Type d\'Inventaire',
                             choices=([('partial', 'Partiel'), ('full', 'Complet')]))


class InventoryProductForm(forms.Form):
    def __init__(self, *args, **kwargs):
        shop = kwargs.pop('shop')
        super().__init__(*args, **kwargs)

        product_choice = ([(None, 'Sélectionner un produit')] +
                          [(str(product.pk)+'/'+str(product.get_unit_display()), product.__str__())
                           for product in Product.objects.filter(shop=shop, is_removed=False)]
                          )
        self.fields['product'].choices = product_choice

    product = forms.ChoiceField(label='Produit', widget=forms.Select(
        attrs={'class': 'form-control selectpicker',
               'data-live-search': 'True', 'required': 'required'}))
    quantity = forms.IntegerField(
        label='En vente',
        widget=forms.NumberInput(
            attrs={'class': 'form-control centered_input quantity',
                   'placeholder': 'Quantité',
                   'min': 0, 'required': 'required'}),
        required=False
    )
    unit_quantity = forms.ChoiceField(
        label='Unité quantité',
        choices=([('UNIT', 'produits'), ('CL', 'cl'),
                  ('L', 'L'), ('G', 'g'), ('KG', 'kg')]),
        widget=forms.Select(
            attrs={'class': 'form-control selectpicker unit_quantity', 'required': 'required'}),
        required=False
    )

    # TODO : Validation


class InventoryListDateForm(forms.Form):
    def __init__(self, **kwargs):
        shop = kwargs.pop('shop')
        super().__init__(**kwargs)
        if shop is None:
            self.fields['shop'] = forms.ModelChoiceField(
                label='Magasin',
                queryset=Shop.objects.all(),
                empty_label='Tous',
                required=False
            )
    date_begin = forms.DateField(
        label='Date de début',
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(attrs={'class': 'datepicker'}),
        required=False
    )
    date_end = forms.DateField(
        label='Date de fin',
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(attrs={'class': 'datepicker'}),
        required=False
    )

Borgia_backend/Borgia/borgia/stocks/templates/stocks/inventory_create.html
{% extends 'base_sober.html' %}
{% load static %}
{% load bootstrap %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-fr_FR.min.js"></script>

<div class="panel panel-default">
  <div class="panel-heading">
    Inventaire du stock du magasin {{ shop }}
  </div>
  <div class="panel-body">
    <form method="post">
      {% csrf_token %}
      {{ additionnal_data_form|bootstrap_horizontal }}
      <h3> Liste des produits :</h3>
      {{ inventory_formset.management_form }}
      {{ inventory_formset.non_form_errors }}
      {% for form in inventory_formset %}
        <div class="category_formset row" style="margin-bottom: 15px">
          <div class="col-md-5">
              {{ form.product }}
            </div>
            <div class="col-md-3 quantity_unit">
              <div class="input-group">
                {{ form.quantity }}
                <span class="input-group-btn">
                  {{ form.unit_quantity }}
                </span>
              </div>
            </div>
        </div>
      {% endfor %}
      <button class="btn btn-success" type="submit">Valider</button>
    </form>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
<script>
$('.category_formset').formset({
  addText: 'Nouveau produit',
  deleteText: 'Supprimer',
  addCssClass: 'add-row btn btn-success btn-sm',
  deleteCssClass: 'delete-row btn btn-warning btn-sm',
  added: function(row) {
    $(row).find('.selectpicker').each(function() {
      $(this).selectpicker()
    })
    $("[id$='product']").change(function(e) {
      update_units.bind(this)(e)
    })
    $(row).find('.selectpicker').trigger('change')
  }
})
$("[id$='product']").change(function(e) {
  update_units.bind(this)(e)
})
$("[id$='product']").trigger('change')
function update_units(e) {
  if (e.target.value) {
    var unit = e.target.value.split('/')[1]
    if (unit !== 'None') {
      if (unit == 'cl') {
        $(this)
          .closest('.row')
          .find('.unit_quantity')
          .find(
            'select option[value="UNIT"], option[value="G"], option[value="KG"]'
          )
          .hide()
        $(this)
          .closest('.row')
          .find('.unit_quantity')
          .find('select option[value="CL"], option[value="L"]')
          .show()
        $(this).closest('.row').find('.unit_quantity').prop('disabled', false)
        $(this).closest('.row').find('.unit_quantity').selectpicker('refresh')
        $(this).closest('.row').find('.unit_quantity').selectpicker('val', 'L')
      }
      if (unit == 'g') {
        $(this)
          .closest('.row')
          .find('.unit_quantity')
          .find(
            'select option[value="UNIT"], option[value="CL"], option[value="L"]'
          )
          .hide()
        $(this)
          .closest('.row')
          .find('.unit_quantity')
          .find('select option[value="G"], option[value="KG"]')
          .show()
        $(this).closest('.row').find('.unit_quantity').prop('disabled', false)
        $(this).closest('.row').find('.unit_quantity').selectpicker('refresh')
        $(this).closest('.row').find('.unit_quantity').selectpicker('val', 'KG')
      }
    } else {
      $(this)
        .closest('.row')
        .find('.unit_quantity')
        .find(
          'select option[value="CL"], option[value="G"], option[value="KG"], option[value="L"]'
        )
        .hide()
      $(this)
        .closest('.row')
        .find('.unit_quantity')
        .find('select option[value="UNIT"]')
        .show()
      $(this).closest('.row').find('.unit_quantity').prop('disabled', false)
      $(this).closest('.row').find('.unit_quantity').selectpicker('refresh')
      $(this).closest('.row').find('.unit_quantity').selectpicker('val', 'UNIT')
    }
  } else {
    $(this)
      .closest('.row')
      .find('.unit_quantity')
      .find(
        'select option[value="UNIT"], option[value="CL"], option[value="G"], option[value="KG"], option[value="L"]'
      )
      .hide()
    $(this).closest('.row').find('.unit_quantity').prop('disabled', true)
    $(this).closest('.row').find('.unit_quantity').selectpicker('refresh')
    $(this).closest('.row').find('.unit_quantity').selectpicker('val', '')
  }
}
</script>
<style>
  .add-row {
    margin: 15px;
  }
  .centered_input {
    text-align: center;
  }
  .delete_row {
    margin-top: 10px;
  }
  .unit_quantity {
    width: 60px;
  }
  .unit_amount {
    width: 100px;
  }
  .input-group-btn > div > button {
    background-color: #eee;
  }
  .input-group .bootstrap-select.form-control {
    z-index: inherit;
  }
</style>
{% endblock %}

Borgia_backend/Borgia/borgia/stocks/templates/stocks/inventory_retrieve.html
{% extends 'base_sober.html' %}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    Détails d'un inventaire du stock du magasin {{ inventory.shop }}
  </div>
  <div class="panel-body">
    <ul>
      <li>Magasin : {{ inventory.shop }}</li>
      <li>Opérateur : {{ inventory.operator }}</li>
      <li>Date : {{ inventory.datetime }}</li>
    </ul>
    <table class="table table-hover table-striped">
      <tr>
        <th>Produit</th>
        <th>Quantité</th>
      </tr>
      {% for inventoryproduct in inventory.inventoryproduct_set.all %}
      <tr>
        <td>{{ inventoryproduct.product }}</td>
        <td>
          {{ inventoryproduct.get_quantity_display }}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/stocks/templates/stocks/stockentry_create.html
{% extends 'base_sober.html' %}
{% load static %}
{% load bootstrap %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-fr_FR.min.js"></script>

<div class="panel panel-default">
  <div class="panel-heading">
    Entrée de stock au magasin {{ shop }}
  </div>
  <div class="panel-body">
    <form method="post">
      {% csrf_token %}
	  {{ add_inventory_form|bootstrap }}
      <h3>Ajouter les produits :</h3>
      {{ stockentry_form.management_form }}
      {% for form in stockentry_form %}
        <div class="category_formset row" style="margin-bottom: 15px">
            <div class="col-md-3">
              {{ form.product }}
            </div>
            <div class="col-md-3 quantity_unit">
              <div class="input-group">
                {{ form.quantity }}
                <span class="input-group-btn">
                  {{ form.unit_quantity }}
                </span>
              </div>
            </div>
            <div class="col-md-3 amount_amount_unit">
              <div class="input-group">
                {{ form.amount }}
                <span class="input-group-btn">
                  {{ form.unit_amount }}
                </span>
              </div>
            </div>
            <div class="col-md-2 product_inventory">
              <div class="input-group">
                {{ form.inventory_quantity }}
                <span class="input-group-btn">
                  {{ form.unit_inventory }}
                </span>
              </div>
            </div>
                {% if form.instance.pk %}{{ form.DELETE }}{% endif %}
        </div>
      {% endfor %}
      <button class="btn btn-success" type="submit">Valider</button>
    </form>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
<script>
$('.category_formset').formset({
  addText: 'Nouveau produit',
  deleteText: 'Supprimer',
  addCssClass: 'btn btn-info',
  // deleteCssClass: 'btn btn-warning', NOT WORKING. Workaround -> adding_btn_class_to_delete()
  added: function(row) {
    $(row).find('.selectpicker').each(function() {
      $(this).selectpicker()
    })
    $("[id$='product']").change(function(e) {
      update_units.bind(this)(e)
    })
    $(row).find('.selectpicker').trigger('change'),
    $(update_inventory_form);
    $(adding_btn_class_to_delete);
  }
})
$("[id$='product']").change(function(e) {
  update_units.bind(this)(e)
})
$("[id$='product']").trigger('change')
function update_units(e) {
  if (e.target.value) {
    var unit = e.target.value.split('/')[1]
    if (unit !== 'None') {
      if (unit == 'cl') {
        $(this)
          .closest('.row')
          .find('.unit_quantity')
          .find(
            'select option[value="UNIT"], option[value="G"], option[value="KG"]'
          )
          .hide()
        $(this)
          .closest('.row')
          .find('.unit_amount')
          .find('select option[value="UNIT"], option[value="KG"]')
          .hide()
        $(this)
          .closest('.row')
          .find('.unit_quantity')
          .find('select option[value="CL"], option[value="L"]')
          .show()
        $(this)
          .closest('.row')
          .find('.unit_amount')
          .find('select option[value="PACKAGE"], option[value="L"]')
          .show()
        $(this).closest('.row').find('.unit_quantity').prop('disabled', false)
        $(this).closest('.row').find('.unit_amount').prop('disabled', false)
        $(this).closest('.row').find('.unit_quantity').selectpicker('refresh')
        $(this).closest('.row').find('.unit_amount').selectpicker('refresh')
        $(this).closest('.row').find('.unit_quantity').selectpicker('val', 'L')
        $(this).closest('.row').find('.unit_amount').selectpicker('val', 'L')
      }
      if (unit == 'g') {
        $(this)
          .closest('.row')
          .find('.unit_quantity')
          .find(
            'select option[value="UNIT"], option[value="CL"], option[value="L"]'
          )
          .hide()
        $(this)
          .closest('.row')
          .find('.unit_amount')
          .find('select option[value="UNIT"], option[value="L"]')
          .hide()
        $(this)
          .closest('.row')
          .find('.unit_quantity')
          .find('select option[value="G"], option[value="KG"]')
          .show()
        $(this)
          .closest('.row')
          .find('.unit_amount')
          .find('select option[value="PACKAGE"], option[value="KG"]')
          .show()
        $(this).closest('.row').find('.unit_quantity').prop('disabled', false)
        $(this).closest('.row').find('.unit_amount').prop('disabled', false)
        $(this).closest('.row').find('.unit_quantity').selectpicker('refresh')
        $(this).closest('.row').find('.unit_amount').selectpicker('refresh')
        $(this).closest('.row').find('.unit_quantity').selectpicker('val', 'KG')
        $(this).closest('.row').find('.unit_amount').selectpicker('val', 'KG')
      }
    } else {
      $(this)
        .closest('.row')
        .find('.unit_quantity')
        .find(
          'select option[value="CL"], option[value="G"], option[value="KG"], option[value="L"]'
        )
        .hide()
      $(this)
        .closest('.row')
        .find('.unit_amount')
        .find('select option[value="KG"], option[value="L"]')
        .hide()
      $(this)
        .closest('.row')
        .find('.unit_quantity')
        .find('select option[value="UNIT"]')
        .show()
      $(this)
        .closest('.row')
        .find('.unit_amount')
        .find('select option[value="UNIT"], option[value="PACKAGE"]')
        .show()
      $(this).closest('.row').find('.unit_quantity').prop('disabled', false)
      $(this).closest('.row').find('.unit_amount').prop('disabled', false)
      $(this).closest('.row').find('.unit_quantity').selectpicker('refresh')
      $(this).closest('.row').find('.unit_amount').selectpicker('refresh')
      $(this).closest('.row').find('.unit_quantity').selectpicker('val', 'UNIT')
      $(this)
        .closest('.row')
        .find('.unit_amount')
        .selectpicker('val', 'PACKAGE')
    }
  } else {
    $(this)
      .closest('.row')
      .find('.unit_quantity')
      .find(
        'select option[value="UNIT"], option[value="CL"], option[value="G"], option[value="KG"], option[value="L"]'
      )
      .hide()
    $(this)
      .closest('.row')
      .find('.unit_amount')
      .find(
        'select option[value="UNIT"], option[value="PACKAGE"], option[value="CL"], option[value="G"], option[value="KG"], option[value="L"]'
      )
      .hide()
    $(this).closest('.row').find('.unit_quantity').prop('disabled', true)
    $(this).closest('.row').find('.unit_amount').prop('disabled', true)
    $(this).closest('.row').find('.unit_quantity').selectpicker('refresh')
    $(this).closest('.row').find('.unit_amount').selectpicker('refresh')
    $(this).closest('.row').find('.unit_quantity').selectpicker('val', '')
    $(this).closest('.row').find('.unit_amount').selectpicker('val', '')
  }
}

function update_inventory_form() {
    var val = $('#id_isAddingInventory').find(':selected').val();
    if (val == 'with') {
        $('.product_inventory').show();
    }
    else if (val == 'without') {
        $('.product_inventory').hide();
    };
};
function adding_btn_class_to_delete() {
    var delete_button = $('.delete-row'); // Default class of delete link
    delete_button.addClass('btn btn-warning');
};

$(update_inventory_form);
$(adding_btn_class_to_delete);
$('#id_isAddingInventory').change(update_inventory_form);


</script>
<style>
    .centered_input {
    text-align: center;
    }
    .unit_quantity {
    width: 60px;
    }
    .unit_amount {
    width: 60px;
    }
    .input-group-btn > div > button {
    background-color: #eee;
    }
    .input-group .bootstrap-select.form-control {
    z-index: inherit;
    }
</style>
{% endblock %}