Borgia_backend/Borgia/borgia/borgia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)

from django.contrib import admin
from django.urls import include, path

from borgia.views import ManagersWorkboard, MembersWorkboard, ModulesLoginView
from configurations.urls import configurations_patterns
from events.urls import events_patterns
from finances.urls import finances_patterns
from modules.urls import modules_patterns
from sales.urls import sales_patterns
from shops.urls import shops_patterns
from stocks.urls import stocks_patterns
from users.urls import users_patterns

urlpatterns = [
    path('api-auth/', include('rest_framework.urls',
                              namespace='rest_framework')),
    path('admin/', admin.site.urls),
    # AUTHENTIFICATIONS
    path('', ModulesLoginView.as_view(), name='url_login'),
    path(
        'auth/',
        include([
            path('login/', ModulesLoginView.as_view(), name='url_login'),
            path('logout/', LogoutView.as_view(), name='url_logout'),
            path('password_change/',
                 PasswordChangeView.as_view(),
                 name='password_change'),
            path('password_change/done/',
                 PasswordChangeDoneView.as_view(),
                 name='password_change_done'),
            path('password_reset/',
                 PasswordResetView.as_view(),
                 name='password_reset'),
            path('password_reset/done/',
                 PasswordResetDoneView.as_view(),
                 name='password_reset_done'),
            path('reset/<uidb64>/<token>/',
                 PasswordResetConfirmView.as_view(),
                 name='password_reset_confirm'),
            path('reset/done/',
                 PasswordResetCompleteView.as_view(),
                 name='password_reset_complete'),
        ])),
    # WORKBOARDS
    path('members/', MembersWorkboard.as_view(), name='url_members_workboard'),
    path('managers/',
         ManagersWorkboard.as_view(),
         name='url_managers_workboard'),

    ### APPS ###
    path('', include(configurations_patterns)),
    path('', include(events_patterns)),
    path('', include(finances_patterns)),
    path('', include(modules_patterns)),
    path('', include(sales_patterns)),
    path('', include(shops_patterns)),
    path('', include(stocks_patterns)),
    path('', include(users_patterns))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Cette ligne permet d'utiliser le dossier MEDIA en
# dev (en prod c'est automatique)

Borgia_backend/Borgia/borgia/finances/urls.py
from django.urls import include, path

from finances.views import (ExceptionnalMovementList,
                            ExceptionnalMovementRetrieve, RechargingCreate,
                            RechargingList, RechargingRetrieve,
                            SelfLydiaConfirm, SelfLydiaCreate,
                            SelfTransactionList, TransfertCreate,
                            TransfertList, TransfertRetrieve,
                            UserExceptionnalMovementCreate,
                            self_lydia_callback)

finances_patterns = [
    path('finances/', include([
        path('transactions/', SelfTransactionList.as_view(),
             name='url_self_transaction_list'),
        # TO USERS
        path('users/<int:user_pk>/', include([
            path('exceptionnal_movement/create/', UserExceptionnalMovementCreate.as_view(),
                 name='url_user_exceptionnalmovement_create'),
            path('rechargings/create', RechargingCreate.as_view(),
                 name='url_recharging_create')
        ])),
        # RECHARGINGS
        path('rechargings/', include([
            path('', RechargingList.as_view(), name='url_recharging_list'),
            path('<int:recharging_pk>/', RechargingRetrieve.as_view(),
                 name='url_recharging_retrieve')
        ])),
        # TRANSFERTS
        path('transferts/', include([
            path('', TransfertList.as_view(), name='url_transfert_list'),
            path('create/', TransfertCreate.as_view(),
                 name='url_transfert_create'),
            path('<int:transfert_pk>/', TransfertRetrieve.as_view(),
                 name='url_transfert_retrieve')
        ])),
        # EXCEPTIONNAL MOVEMENTS
        path('exceptionnal_movements/', include([
            path('', ExceptionnalMovementList.as_view(),
                 name='url_exceptionnalmovement_list'),
            path('<int:exceptionnalmovement_pk>/', ExceptionnalMovementRetrieve.as_view(),
                 name='url_exceptionnalmovement_retrieve')
        ])),
        # Lydias
        path('lydias/', include([
            path('callback/', self_lydia_callback,
                 name='url_self_lydia_callback'),
            path('create/', SelfLydiaCreate.as_view(),
                 name='url_self_lydia_create'),
            path('confirm/', SelfLydiaConfirm.as_view(),
                 name='url_self_lydia_confirm')
        ]))
    ]))
]

Borgia_backend/Borgia/borgia/sales/urls.py
from django.urls import include, path

from sales.views import SaleList, SaleRetrieve


sales_patterns = [

    path('shops/<int:shop_pk>/sales/', include([
        path('', SaleList.as_view(), name='url_sale_list'),
        path('<int:sale_pk>/', SaleRetrieve.as_view(),
        name='url_sale_retrieve')
    ]))
]

Borgia_backend/Borgia/borgia/finances/models.py
import decimal

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MinValueValidator, RegexValidator
from django.db import models
from django.utils.timezone import now

from users.models import User

# TODO: harmonization of methods name of Cash, Lydia, Cheque.
# TODO: harmonization of attributes singular/plurial (especially in Payment).
# TODO: event line in tables users, products/payments and function.


class Recharging(models.Model):
    """
    Allow an operator to recharge (supply money) the balance of a sender
    """
    datetime = models.DateTimeField('Date', default=now)
    sender = models.ForeignKey(User, related_name='sender_recharging',
                               on_delete=models.CASCADE)
    operator = models.ForeignKey(User, related_name='operator_recharging',
                                 on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    solution_id = models.PositiveIntegerField()
    content_solution = GenericForeignKey('content_type', 'solution_id')

    class Meta:
        """
        Define Permissions for Recharging.

        :note:: Initial Django Permission (add, view) are added.
        """
        default_permissions = ('add', 'view',)

    def __str__(self):
        return 'Rechargement de ' + str(self.amount()) + '€.'

    def amount(self):
        return self.content_solution.amount

    def pay(self):
        self.sender.credit(self.amount())


class Transfert(models.Model):
    datetime = models.DateTimeField('Date', default=now)
    justification = models.TextField('Justification', null=True, blank=True)
    sender = models.ForeignKey(User, related_name='sender_transfert',
                               on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='recipient_transfert',
                                  on_delete=models.CASCADE)
    amount = models.DecimalField('Montant', default=0, decimal_places=2,
                                 max_digits=9,
                                 validators=[MinValueValidator(decimal.Decimal(0))])

    class Meta:
        """
        Define Permissions for Recharging.

        :note:: Initial Django Permission (add, view) are added.
        """
        default_permissions = ('add', 'view',)

    def __str__(self):
        return 'Transfert de ' + self.sender.__str__() + ' à ' + self.recipient.__str__() +', ' + self.justification

    def pay(self):
        if self.sender.debit != self.recipient.credit:
            self.sender.debit(self.amount)
            self.recipient.credit(self.amount)


class ExceptionnalMovement(models.Model):
    datetime = models.DateTimeField('Date', default=now)
    justification = models.TextField('Justification', null=True, blank=True)
    operator = models.ForeignKey(User, related_name='sender_exceptionnal_movement',
                                 on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='recipient_exceptionnal_movement',
                                  on_delete=models.CASCADE)
    amount = models.DecimalField('Montant', default=0, decimal_places=2,
                                 max_digits=9,
                                 validators=[MinValueValidator(decimal.Decimal(0))])
    is_credit = models.BooleanField(default=False)

    class Meta:
        """
        Define Permissions for Recharging.

        :note:: Initial Django Permission (add, view) are added.
        """
        default_permissions = ('add', 'view',)

    def __str__(self):
        return 'Mouvement exceptionnel de ' + str(self.amount) + '€, ' + self.justification

    def pay(self):
        '''
        Add/Remove money from recipient
        '''
        if self.is_credit:
            self.recipient.credit(self.amount)
        else:
            self.recipient.debit(self.amount)


class BaseRechargingSolution(models.Model):
    """
    Base model for recharging solutions.
    """
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField('Montant', default=0, decimal_places=2,
                                 max_digits=9,
                                 validators=[MinValueValidator(decimal.Decimal(0))])

    class Meta:
        """
        Remove default permissions for base and children.
        """
        abstract = True
        default_permissions = ()


class Cheque(BaseRechargingSolution):
    """
    Define a type of recharging made by a bank cheque.

    :note:: Related to a unique User.

    :param is_cashed: true if the cheque is cashed by treasurers, mandatory.
    :param signature_date: signature date of the cheque (written on the paper),
    mandatory.
    :param cheque_number: number of the cheque (written on the paper),
    mandatory.
    :type is_cashed: boolean, default False
    :type signature_date: date string, default now
    :type cheque_number: string, must match ^[0-9]{7}$
    """
    is_cashed = models.BooleanField('Est encaissé', default=False)
    signature_date = models.DateField('Date de signature', default=now)
    cheque_number = models.CharField('Numéro de chèque', max_length=7,
                                     validators=[
                                         RegexValidator('^[0-9]{7}$',
                                                        '''Numéro de chèque
                                                        invalide''')])

    def __str__(self):
        return 'Cheque de ' + str(self.amount) + '€, n°' + self.cheque_number


class Cash(BaseRechargingSolution):
    """
    Define a type of payment made by a phycial money (cash).

    :note:: Related to a unique User.
    """

    def __str__(self):
        return 'Cash de ' + str(self.amount) + '€'


class Lydia(BaseRechargingSolution):
    """
    Define a transaction by the provider Lydia.

    :note:: Related to an unique User.

    :param date_operation: date of transaction, mandatory.
    :param id_from_lydia: unique number given by the provider for each
    transaction, mandatory. Must be unique.
    :param banked: true if the money was banked by treasurer, mandatory.
    :param date_banked: only if banked is true.
    :type date_operation: date string, default now
    :type id_from_lydia: string
    :type banked: boolean, default False
    :type date_banked: fate string
    """
    date_operation = models.DateField('Date', default=now)
    id_from_lydia = models.CharField('Numéro unique', max_length=255)
    is_online = models.BooleanField('Paiement en ligne', default=True)
    fee = models.DecimalField('Frais lydia', default=0, decimal_places=2,
                              max_digits=9,
                              validators=[MinValueValidator(decimal.Decimal(0))])

    def __str__(self):
        return 'Lydia de ' + str(self.amount) + '€, n°' + self.id_from_lydia

Borgia_backend/Borgia/borgia/finances/templates/finances/exceptionnalmovement_list.html
{% extends 'base_sober.html' %}
{% load bootstrap %}

{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
          Recherche de mouvements exceptionnels
        </div>
        <div class="panel-body">
          <form action="" method="post" class="form-horizontal">
            {% csrf_token %}
            {{ form|bootstrap_horizontal }}
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-2">
                <button type="submit" class="btn btn-primary">Recherche</button>
                <a class="btn btn-warning" href="">Remise à zéro</a>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          Résultats
        </div>
          <table class="table table-hover table-striped">
            <tr>
                <th>Opérateur</th>
                <th>Utilisateur</th>
                <th>Date</th>
                <th>Heure</th>
                <th>Montant</th>
                <th>Type</th>
                <th>Détail</th>
            </tr>
            {% for exceptionnalmovement in exceptionnalmovement_list %}
            <tr class="{% if exceptionnalmovement.is_credit %}success{% else %}danger{% endif %}">
                <td>{{ exceptionnalmovement.operator }}</td>
                <td>{{ exceptionnalmovement.recipient }}</td>
                <td>{{ exceptionnalmovement.datetime|date:"SHORT_DATE_FORMAT" }}</td>
                <td>{{ exceptionnalmovement.datetime|time:"H:i" }}</td>
                <td>{{ exceptionnalmovement.amount }}€</td>
                <td>{% if exceptionnalmovement.is_credit %}Crédit{% else %}Débit{% endif %}</td>
                <td>
                  <a href="{% url 'url_exceptionnalmovement_retrieve' exceptionnalmovement_pk=exceptionnalmovement.pk %}">Détail</a>
                </td>
            </tr>
            {% endfor %}
          </table>
        </div>
{% endblock %}

Borgia_backend/Borgia/borgia/finances/templates/finances/exceptionnalmovement_retrieve.html
{% extends 'base_sober.html' %}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    Détails d'un mouvement exceptionnel sur un compte
  </div>
  <div class="panel-body">
    <ul>
      <li>Opérateur : {{ exceptionnalmovement.operator }}</li>
      <li>Receveur : {{ exceptionnalmovement.recipient }}</li>
      <li>Date : {{ exceptionnalmovement.datetime }}</li>
      <li>Montant : {{ exceptionnalmovement.amount }}€</li>
      <li>Type : {% if exceptionnal_movement.is_credit %}Crédit{% else %}Débit{% endif %}</li>
      <li>Justification : {{ exceptionnalmovement.justification }}</li>
    </ul>
  </div>
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/finances/templates/finances/recharging_list.html
{% extends 'base_sober.html' %}
{% load bootstrap %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-fr_FR.min.js"></script>

    <div class="panel panel-primary">
        <div class="panel-heading">
          Recherche de rechargements
        </div>
        <div class="panel-body">
          <form action="" method="post" class="form-horizontal">
            {% csrf_token %}
            {{ form|bootstrap_horizontal }}
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-2">
                <button type="submit" class="btn btn-primary">Recherche</button>
                <a class="btn btn-warning" href="">Remise à zéro</a>
                <span style="opacity: 0.54; margin-left: 5px;">Les 1000 premiers résultats sont affichés</span>
              </div>
            </div>
          </form>
        </div>
      </div>
    <div class="panel panel-default">
        <div class="panel-heading">
          Synthèse
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-4">
              <h4>Total</h4>
              <ul>
                <li>Nombre : {{ info.total.nb }}</li>
                <li>Total : {{ info.total.total }}€</li>
              </ul>
            </div>
            <div class="col-md-2">
              <h4>Espèces</h4>
              <ul>
                <li>Nombre : {{ info.cash.nb }}</li>
                <li>Total : {{ info.cash.total }}€</li>
              </ul>
            </div>
            <div class="col-md-2">
              <h4>Chèques</h4>
              <ul>
                <li>Nombre : {{ info.cheque.nb }}
                  {% if info.cheque.nb %}
                  <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#list_cheque">
                    Détails
                  </button>
                  {% endif %}
                </li>
                <li>Total : {{ info.cheque.total }}€</li>
              </ul>
            </div>
            <div class="col-md-2">
              <h4>Lydia face à face</h4>
              <ul>
                <li>Nombre : {{ info.lydia_face2face.nb }}
                  {% if info.lydia_face2face.nb %}
                  <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#list_lydia_face2face">
                    Détails
                  </button>
                  {% endif %}
                </li>
                <li>Total : {{ info.lydia_face2face.total }}€</li>
              </ul>
            </div>
            <div class="col-md-2">
              <h4>Lydia automatique</h4>
              <ul>
                <li>Nombre : {{ info.lydia_online.nb }}
                  {% if info.lydia_online.nb %}
                  <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#list_lydia_oneline">
                    Détails
                  </button>
                  {% endif %}
                </li>
                <li>Total : {{ info.lydia_online.total }}€</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          Résultats
        </div>
          <table class="table table-hover table-striped">
            <tr>
                <th>Opérateur</th>
                <th>Utilisateur</th>
                <th>Date</th>
                <th>Heure</th>
                <th>Montant</th>
                <th>Type</th>
                <th>Détail</th>
            </tr>
            {% for recharging in recharging_list %}
            <tr>
                <td>{{ recharging.operator }}</td>
                <td>{{ recharging.sender }}</td>
                <td>{{ recharging.datetime|date:"SHORT_DATE_FORMAT" }}</td>
                <td>{{ recharging.datetime|time:"H:i" }}</td>
                <td>{{ recharging.content_solution.amount }}€</td>
                <td>{{ recharging.content_solution }}</td>
                <td>
                  <a href="{% url 'url_recharging_retrieve' recharging_pk=recharging.pk %}">Détail</a>
                </td>
            </tr>
            {% endfor %}
          </table>
        </div>

<!-- Modal -->
<div class="modal fade" id="list_cheque" tabindex="-1" role="dialog" aria-labelledby="Liste chèques">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Liste des chèques</h4>
      </div>
      <div class="modal-body">
        <table class="table table-default table-hover">
          <thead>
            <tr>
              <th>Numéro</th>
              <th>Montant</th>
              <th>Signataire</th>
              <th>Date de signature</th>
              <th>Ordre</th>
            </tr>
          </thead>
          <tbody>
            {% for c in info.cheque.ids %}
              <tr>
                <td>{{ c.cheque_number }}</td>
                <td>{{ c.amount }}€</td>
                <td>{{ c.sender }}</td>
                <td>{{ c.signature_date }}</td>
                <td>{{ c.recipient }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="list_lydia_oneline" tabindex="-1" role="dialog" aria-labelledby="Liste Lydia en ligne">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Liste des Lydia en ligne</h4>
      </div>
      <div class="modal-body">
        <table class="table table-default table-hover">
          <thead>
            <tr>
              <th>Numéro</th>
              <th>Montant</th>
              <th>Payeur</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            {% for ly in info.lydia_online.ids %}
              <tr>
                <td>{{ ly.id_from_lydia }}</td>
                <td>{{ ly.amount }}€</td>
                <td>{{ ly.sender }}</td>
                <td>{{ ly.date_operation }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="list_lydia_face2face" tabindex="-1" role="dialog" aria-labelledby="Liste des Lydia en face à face">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Liste des Lydia en face à face</h4>
      </div>
      <div class="modal-body">
        <table class="table table-default table-hover">
          <thead>
            <tr>
              <th>Numéro</th>
              <th>Montant</th>
              <th>Payeur</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            {% for ly in info.lydia_face2face.ids %}
              <tr>
                <td>{{ ly.id_from_lydia }}</td>
                <td>{{ ly.amount }}€</td>
                <td>{{ ly.sender }}</td>
                <td>{{ ly.date_operation }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/finances/templates/finances/recharging_retrieve.html
{% extends 'base_sober.html' %}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    Détails d'un rechargement de compte
    <a class="btn btn-default btn-xs" href="{% url 'url_recharging_list' %}">Liste</a>
  </div>
  <div class="panel-body">
    <ul>
      <li>Opérateur : {{ recharging.operator }}</li>
      <li>Acheteur : {{ recharging.sender }}</li>
      <li>Date & heure : {{ recharging.datetime }}</li>
      <li>Montant : {{ recharging.content_solution.amount }}€</li>
      <li>Type : {{ recharging.content_solution }}
    </ul>
  </div>
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/finances/templates/finances/self_lydia_button.html
{% extends 'base_sober.html' %}
{% load static %}
{% load l10n %}
{% load bootstrap %}

{% block content %}
<script type="text/javascript" src="{% static 'Lydia_assets/LYDIASDK.js' %}"></script>

<div class="panel panel-default">
    <div class="panel-heading">
        Crédit du compte avec Lydia
    </div>
    <div class="panel-body">
    
        <p>
            <strong>Montant à payer :</strong> {{ total_amount|unlocalize }}€
            {% if enable_fee_lydia %}
                <br />
                <strong>Frais de commission Lydia :</strong> {{ fee_amount|unlocalize }}€
                <br />
                <strong>Montant rechargé :</strong> {{ recharging_amount|unlocalize }}€
            {% endif %}
        </p>
        <p>
          <strong>Numéro de téléphone :</strong> {{ tel_number }}
        </p>
        <a class="btn btn-warning" href="{% url 'url_self_lydia_create' %}">Modifier</a>
        <div role="button" id="lydiaButton" style="margin-top: 10px"></div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#lydiaButton').payWithLYDIA({
            amount: {{ total_amount|unlocalize }},
            vendor_token: '{{ vendor_token }}',
            recipient: '{{ tel_number }}', //cellphone or email of your client
            message : '{{ message }}', //object of the payment
            render : '<img src="https://lydia-app.com/assets/img/paymentbutton.png" />', //button image
            // The client will be redirect to this URL after the payment
            browser_success_url : "{{ confirm_url }}",
            // This URL will be called by our server after the payment so you can update the order on your database
            confirm_url : "{{ callback_url }}?user_pk={{ user.pk }}"
        });
    });
</script>
{% endblock %}

Borgia_backend/Borgia/borgia/finances/templates/finances/self_lydia_confirm.html
{% extends 'base_sober.html' %}

{% block content %}
<div class="panel panel-success">
  <div class="panel-heading">
    Confirmation de la commande Lydia {{ transaction }}
  </div>
  <div class="panel-body">
    <p>Votre compte a bien été crédité via un virement Lydia.</p>
    <p>Le crédit est immédiat.
      En cas de problème quelconque, n'hésitez pas à contacter le
      support de Borgia ou un trésorier de l'association'.</p>
  </div>
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/finances/templates/finances/self_lydia_create.html
{% extends 'base_sober.html' %}
{% load bootstrap %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        Crédit du compte avec Lydia
    </div>
    <div class="panel-body">
        {% if state == "disabled" %}
            <p>Le rechargement par Lydia est désactivé, il n'est pas actuellement possible d'utiliser cette fonctionnalité.</p>
        {% elif state == "undefined" %}
            <p>Le rechargement par Lydia n'est pas correctement configuré, il n'est pas actuellement possible d'utiliser cette fonctionnalité.</p>
        {% elif state == "enabled" %}
            <form action="" method="post">
                {% csrf_token %}
                {{ form|bootstrap }}
                <button class="btn btn-success" type="submit">Valider</button>
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}

Borgia_backend/Borgia/borgia/finances/templates/finances/user_supplymoney.html
{% extends 'base_sober.html' %}
{% load bootstrap %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        Ajout d'argent sur le compte de {{ user }}
    </div>
    <div class="panel-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|bootstrap }}
            <input id="type_value" type=hidden name="type_value" value="{{ form.type.value }}" />
            <button class="btn btn-success" type="submit">Ajouter</button>
        </form>
    </div>
</div>

<script>
    // Initialisation de type (erreur de validation)
    $(document).ready(function() {
        check_type();
    });

    // Changement de type
    $('#id_type').change(function() {
        check_type();        //$('#id_sender').trigger('change');
    });

    function check_type() {
        if ($('#id_type option:selected').val() == 'cash') {
            display_cash();
        }
        else if ($('#id_type option:selected').val() == 'cheque') {
            display_cheque();
        }
        else if ($('#id_type option:selected').val() == 'lydia') {
            display_lydia();
        }
    }
    function display_cash() {
        $('label[for=' + 'id_unique_number' + '], input#id_unique_number').hide();
        $('label[for=' + 'id_signature_date' + '], input#id_signature_date').hide();
    }
    function display_cheque() {
        $('label[for=' + 'id_unique_number' + '], input#id_unique_number').show();
        $('label[for=' + 'id_signature_date' + '], input#id_signature_date').show();
    }
    function display_lydia() {
        $('label[for=' + 'id_unique_number' + '], input#id_unique_number').show();
        $('label[for=' + 'id_signature_date' + '], input#id_signature_date').show();
    }
</script>
{% endblock %}